/-
Copyright (c) 2026 Oleg Shabanov. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Oleg Shabanov
-/
module

public meta import Lean
public meta import Lexgen.Internal.Codegen
public meta import Lexgen.Internal.Pipeline
-- The code generated by `lexer` refers to declarations of `Lexgen.Lexer`
-- and `Lexgen.Internal.Pack`.
public import Lexgen.Internal.Pack
public import Lexgen.Lexer

public section

open Lean Elab Command Lexgen.Internal

/-!
# `lexer` syntax

Defines the `lexer` command: its syntax and its elaboration.
-/

namespace Lexgen

/--
Token rules of the `lexer` command
-/
declare_syntax_cat lexgenRule

/--
A rule of a token without a value.
-/
syntax ident ":=" str : lexgenRule

/--
A rule of a token with a value: the name of the token, the type of the value, the pattern, and the
function computing the value from the token's slice.
-/
syntax ident ":" term ":=" str "=>" term : lexgenRule

/--
A skip rule of the `lexer` command: the pattern of the text that is dropped.
-/
syntax skipRule := "skip" str

/--
Declares a lexer: an inductive type with a constructor for each rule but the skip rules, its
`Lexgen.Lexable` instance, and a function `lexer` in its namespace, which creates a `Lexgen.Lexer`
for a string.

Each token rule pairs a constructor with the pattern it matches, usually written as a raw string
literal: `name := r"…"`. A rule `name : α := r"…" => f` also gives the constructor a value of type
`α`, which `f : String.Slice → α` computes from the token's slice. The lexer always takes the
longest match; when several rules match the same text, the one declared earlier wins. If no rule
matches, lexing fails with the byte offset of the failure.

Rules `skip r"…"`, written before the others, match text that is dropped, such as whitespace or
comments; being declared first, they win over other rules matching the same text.

An optional `deriving` clause after the rules derives the listed instances for the token type.
-/
syntax
"lexer" ident "where"
  skipRule*
  ("|" lexgenRule)*
  -- Skip rules after the token rules are accepted only to report them as an error.
  skipRule*
("deriving" ident,+)? : command

/--
Builds two parallel arrays from the token rules and the skip patterns of a `lexer` declaration: one
holds the `RuleInfo` of each rule, the other its pattern.
-/
private meta def getRules (rules : Array (TSyntax `lexgenRule))
    (skipPatterns : Array (TSyntax `str)) : CommandElabM (Array RuleInfo × Array StrLit) := do
  return skipPatterns.map (RuleInfo.skip, ·) ++
  (← rules.mapM fun
    | `(lexgenRule| $tokenName:ident := $pattern) => pure (RuleInfo.simple tokenName, pattern)
    | `(lexgenRule| $tokenName:ident : $valueType := $pattern => $func) =>
      pure (RuleInfo.converted tokenName valueType func, pattern)
    | _ => throwUnsupportedSyntax)
  |>.unzip

/--
Checks the names of a `lexer` declaration: the type must not be declared yet, and the token names
must be distinct and differ from `lexer`.

Runs before any code is generated, so that errors are reported on the names themselves rather than
on the generated code.
-/
private meta def checkNames (typeName : Ident) (tokenNames : Array Ident) : CommandElabM Unit := do
  -- Resolves the type name as `inductive` does and fails if it is already declared.
  discard <| withRef typeName <| mkDeclName (← getCurrNamespace) {} typeName.getId

  let mut seen : Std.HashSet Name := {}

  for token in tokenNames do
    if token.getId == `lexer then
      logErrorAt token m!"`lexer` is taken by the generated function `{typeName}.lexer`"
    else if seen.contains token.getId then
      logErrorAt token m!"duplicate token name `{token}`"
    seen := seen.insert token.getId
  if ← MonadLog.hasErrors then
    throwAbortCommand

/--
Reports each of `errors` on the pattern of the rule it concerns. `patterns` are indexed by rule
number.
-/
private meta def throwConversionErrors (patterns : Array StrLit) (errors : Array ConversionError) :
    CommandElabM α := do
  for error in errors do
    match error with
    | .noRules => logError "a lexer needs at least one rule"
    | .invalidPattern rule offset msg =>
      logErrorAt patterns[rule]! m!"offset {offset}: {msg}"
    | .matchesEmpty rule =>
      logErrorAt
        patterns[rule]!
        "this rule matches the empty string, so the lexer would loop on it"
  throwAbortCommand

/--
Builds the `DFA` from the patterns, or throws an error if they cannot be converted.
-/
private meta def getDFA (patterns : Array StrLit) : CommandElabM DFA :=
  match rulesToDFA (patterns.toList.map TSyntax.getString) with
    | .ok    dfa    => pure dfa
    | .error errors => throwConversionErrors patterns errors

/--
Reports each skip rule written after the token rules.
-/
private meta def throwLateSkipError (statements : Array Syntax) : CommandElabM α := do
  for statement in statements do
    logErrorAt
      statement
      "skip rules must come before the token rules"
  throwAbortCommand

/--
Warns on the pattern of each rule of `dfa` that never produces a match.
-/
private meta def logDeadRules (patterns : Array StrLit) (dfa : DFA) : CommandElabM Unit := do
  let live := dfa.liveRules
  let dead := patterns.zipIdx.filter fun (_, i) => !live.contains i
  for (pattern, _) in dead do
    logWarningAt
      pattern
      "this rule never produces a match: other rules always win over it"

/--
Elaborates a `lexer` declaration: checks its rules and builds their `DFA`, then generates the token
type, a function per `DFA` state, the `Lexable` instance of the type and the function `lexer`.
-/
elab_rules : command
  | `(
      lexer $typeName:ident where
        $[skip $skipPatterns]*
        $[| $rules:lexgenRule]*
      $[deriving $[$derivings:ident],*]?
    ) => do
    let (ruleInfos, patterns) ← getRules rules skipPatterns
    if ruleInfos.size > 2 ^ ruleBits - 1 then
      throwError "too many rules"
    checkNames typeName (ruleInfos.filterMap (·.name))
    let dfa ← getDFA patterns
    logDeadRules patterns dfa
    for cmd in ← buildLexer typeName ruleInfos dfa derivings do
      elabCommand cmd
      -- The later declarations refer to the earlier ones, so once one of them fails the rest only
      -- add noise.
      if ← MonadLog.hasErrors then
        throwAbortCommand
  | `(
      lexer $_:ident where
        $_*
        $[| $rules:lexgenRule]*
        $lateSkips*
      $[deriving $[$derivings:ident],*]?
    ) =>
    throwLateSkipError lateSkips

end Lexgen
