/-
Copyright (c) 2026 Oleg Shabanov. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Oleg Shabanov
-/
module

public meta import Lean
public meta import Lexgen.Internal.Codegen
public meta import Lexgen.Internal.Pipeline
-- The code generated by `lexer` refers to declarations of `Lexgen.Lexer`
-- and `Lexgen.Internal.Pack`.
public import Lexgen.Internal.Pack
public import Lexgen.Lexer

public section

open Lean Elab Command Lexgen.Internal

/-!
# `lexer` syntax

Defines the `lexer` command: its syntax and its elaboration.
-/

namespace Lexgen

/--
Token rules of the `lexer` command
-/
declare_syntax_cat lexgenRule

/--
A rule of a token without a value.
-/
syntax ident ":=" str : lexgenRule

/--
A rule of a token with a value: the name of the token, the type of the value, the regex, and the
function computing the value from the token's slice.
-/
syntax ident ":" term ":=" str "=>" term : lexgenRule

/--
A skip rule of the `lexer` command: the regex of the text that is dropped.
-/
syntax skipRule := "skip" str

/--
Declares a lexer: an inductive type with a constructor for each rule but the skip rules, its
`Lexgen.Lexable` instance, and a function `lexer` in its namespace, which creates a `Lexgen.Lexer`
for a string.

Each token rule pairs a constructor with the regex it matches, usually written as a raw string
literal: `name := r"…"`. A rule `name : α := r"…" => f` also gives the constructor a value of type
`α`, which `f : String.Slice → α` computes from the token's slice. The lexer always takes the
longest match; when several rules match the same text, the one declared earlier wins. If no rule
matches, lexing fails with the byte offset of the failure.

Rules `skip r"…"`, written before the others, match text that is dropped, such as whitespace or
comments; being declared first, they win over other rules matching the same text.

An optional `deriving` clause after the rules derives the listed instances for the token type.
-/
syntax
"lexer" ident "where"
  skipRule*
  ("|" lexgenRule)*
  skipRule*
("deriving" ident,+)? : command

/--
Checks the names of a `lexer` declaration before any code is generated, so that errors are reported
on the names themselves rather than on the generated code: the type must not be declared yet, and
token names must be distinct and differ from `lexer`.
-/
private meta def checkNames (typeName : Ident) (tokenNames : Array Ident) : CommandElabM Unit := do
  -- Resolves the type name as `inductive` does and fails if it is already declared.
  discard <| withRef typeName <| mkDeclName (← getCurrNamespace) {} typeName.getId

  let mut seen : Std.HashSet Name := {}
  let mut failed := false

  for token in tokenNames do
    if token.getId == `lexer then
      logErrorAt token m!"`lexer` is taken by the generated function `{typeName}.lexer`"
      failed := true
    else if seen.contains token.getId then
      logErrorAt token m!"duplicate token name `{token}`"
      failed := true
    seen := seen.insert token.getId
  if failed then
    throwAbortCommand

/--
Reports a `ConversionError` on the patterns it concerns: the pattern of a rule that fails to parse,
or the pattern of each rule that matches the empty string. `patterns` are indexed by rule number.
-/
private meta def throwConversionError (patterns : Array StrLit) :
    ConversionError → CommandElabM α
  | .noRules => throwError "a lexer needs at least one rule"
  | .invalidPattern rule offset msg =>
    throwErrorAt patterns[rule]! m!"offset {offset}: {msg}"
  | .matchesEmpty rules => do
    for rule in rules do
      logErrorAt
        patterns[rule]!
        "this rule matches the empty string, so the lexer would loop on it"
    throwAbortCommand

/--
Reports each skip rule written after the token rules.
-/
private meta def throwLateSkipError (statements : Array Syntax) : CommandElabM α := do
  for statement in statements do
    logErrorAt
      statement
      "skip rules must come before the token rules"
  throwAbortCommand

/--
Warns on the pattern of each rule of `dfa` that never produces a match.
-/
private meta def logDeadRules (patterns : Array StrLit) (dfa : DFA) : CommandElabM Unit := do
  let live := dfa.liveRules
  let dead := patterns.zipIdx.filter fun (_, i) => !live.contains i
  for (pattern, _) in dead do
    logWarningAt
      pattern
      "this rule never produces a match: other rules always win over it"

elab_rules : command
  | `(
      lexer $typeName:ident where
        $[skip $skipPatterns]*
        $[| $rules:lexgenRule]*
      $[deriving $[$derivings:ident],*]?
    ) => do
    let mut ruleInfos := #[]
    let mut patterns := #[]
    for pattern in skipPatterns do
      ruleInfos := ruleInfos.push RuleInfo.skip
      patterns  := patterns.push pattern
    for rule in rules do
      match rule with
      | `(lexgenRule| $tokenName:ident := $pattern) =>
        ruleInfos := ruleInfos.push (RuleInfo.simple tokenName)
        patterns  := patterns.push pattern
      | `(lexgenRule| $tokenName:ident : $valueType := $pattern => $func) =>
        ruleInfos := ruleInfos.push (RuleInfo.converted tokenName valueType func)
        patterns  := patterns.push pattern
      | _ => throwUnsupportedSyntax
    checkNames typeName (ruleInfos.filterMap (·.name))
    let dfa ← match rulesToDFA (patterns.toList.map TSyntax.getString) with
      | .ok    dfa => pure dfa
      | .error err => throwConversionError patterns err
    logDeadRules patterns dfa
    for cmd in ← buildLexer typeName ruleInfos dfa derivings do
      elabCommand cmd
  | `(
      lexer $_:ident where
        $_*
        $[| $rules:lexgenRule]*
        $lateSkips*
      $[deriving $[$derivings:ident],*]?
    ) =>
    throwLateSkipError lateSkips

end Lexgen
